FROM python:3.8-slim
WORKDIR /opt/led-pi/light-server
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential

COPY ./light-server/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./light-server/* ./

CMD ["python", "test.py"]
